test

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,4 +1,4 @@
-name: "Build and Push Docker Image to GHCR or GAR"
+name: Build and Push Docker Image to GHCR or GAR
 
 on:
   workflow_dispatch:
@@ -15,9 +15,7 @@ on:
 
 env:
   REGISTRY: ghcr.io
-  # github.repository as <account>/<repo>
-  #https://asia-south1-docker.pkg.dev/avian-voice-433417-d5/asia-south1-docker-images-multiregion-prod
-  IMAGE_NAME:  '${{ github.event.repository.name }}'
+  IMAGE_NAME: '${{ github.event.repository.name }}'
   IMAGE_ID: 'ghcr.io/${{ github.event.repository.name }}/temp:v01'
   GAR_NAME: 'asia-south1-docker.pkg.dev'
   GAR_REPO_NAME: 'asia-south1-docker-images-multiregion-prod'
@@ -29,37 +27,36 @@ env:
 
 jobs:
   validate_branch:
-   runs-on: ubuntu-latest
-   steps:
-    - name: Check Branch
-      run: |
-        echo "You are using a  ${{ github.ref_name }} ${{ github.head_ref }}branch with ${{github.event_name}} as action"
-        if ["${{ github.ref_name }}" == 'release' ] || [ "${{ github.base_ref }}" == 'release' ] || [[ "${{ github.ref_name }}" == feature* || "${{ github.base_ref }}" == feature* ]] || [[ "${{ github.ref_name }}" == release* || "${{ github.base_ref }}" == release* ]] || [[ "${{ github.ref_name }}" == bugfix* || "${{ github.base_ref }}" == bugfix* ]]; then
-          echo "The branch follows 'release*/feature*/bugfix*' workflows."
-          echo "workflow_name=nonprod" >> $GITHUB_ENV
-          echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
-          echo "PAC_ACTION=continue" >> $GITHUB_ENV
-        
-        elif [ "${{ github.ref_name }}" == 'main' ] || [ "${{ github.base_ref }}" == 'main' ] || [[ "${{ github.ref_name }}" == hotfix* ]] || [[ "${{ github.base_ref }}" == hotfix* ]]; then
-          echo "The branch follows 'prod' workflows."
-          echo "workflow_name=prod" >> $GITHUB_ENV
-          echo "REGISTRY=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}" >> $GITHUB_ENV
-          if [[ "${{ github.ref_name }}" == hotfix* || "${{ github.base_ref }}" == hotfix* ]]; then
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Branch
+        run: |
+          echo "You are using a ${{ github.ref_name }} branch with ${{ github.event_name }} as action"
+          if [[ "${{ github.ref_name }}" == 'release' || "${{ github.base_ref }}" == 'release' || "${{ github.ref_name }}" == feature* || "${{ github.base_ref }}" == feature* || "${{ github.ref_name }}" == release* || "${{ github.base_ref }}" == release* || "${{ github.ref_name }}" == bugfix* || "${{ github.base_ref }}" == bugfix* ]]; then
+            echo "The branch follows 'release*/feature*/bugfix*' workflows."
+            echo "workflow_name=nonprod" >> $GITHUB_ENV
+            echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
             echo "PAC_ACTION=continue" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == 'main' || "${{ github.base_ref }}" == 'main' || "${{ github.ref_name }}" == hotfix* || "${{ github.base_ref }}" == hotfix* ]]; then
+            echo "The branch follows 'prod' workflows."
+            echo "workflow_name=prod" >> $GITHUB_ENV
+            echo "REGISTRY=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}" >> $GITHUB_ENV
+            if [[ "${{ github.ref_name }}" == hotfix* || "${{ github.base_ref }}" == hotfix* ]]; then
+              echo "PAC_ACTION=continue" >> $GITHUB_ENV
+            else
+              echo "PAC_ACTION=break" >> $GITHUB_ENV
+            fi
+            echo "IMAGE_ID=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}/${{ github.event.repository.name }}" >> $GITHUB_ENV
+            echo "Imageid is $IMAGE_ID"
           else
-          echo "PAC_ACTION=break" >> $GITHUB_ENV
+            echo "The branch is invalid. Use 'gcp-release' or 'z5-main' as your branch."
+            env.workflow_name='Invalid'
+            exit 1
           fi
-          echo "IMAGE_ID=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}/${{ github.event.repository.name }}" >> $GITHUB_ENV
-          echo "Imageid is $IMAGE_ID"
-        else
-          echo "The branch is invalid. Use 'gcp-release' or 'z5-main' as your branch."
-          env.workflow_name='Invalid'
-          exit 1
-        fi
-   outputs:
-    op_workflow_name: ${{ env.workflow_name }}
-    op_registry: ${{ env.REGISTRY }}
-    op_pac_action: ${{ env.PAC_ACTION }}
+    outputs:
+      op_workflow_name: ${{ env.workflow_name }}
+      op_registry: ${{ env.REGISTRY }}
+      op_pac_action: ${{ env.PAC_ACTION }}
 
   build-docker-image:
     outputs:
@@ -87,22 +84,19 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Log into Google Artifact registry 
-        if: needs.validate_branch.outputs.op_workflow_name == 'prod' &&  github.event_name =='push'
+        if: needs.validate_branch.outputs.op_workflow_name == 'prod' && github.event_name =='push'
         uses: docker/login-action@v3
         with: 
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-            # Extract metadata (tags, labels) for Docker
-      # https://github.com/docker/metadata-action
+
       - name: Extract Docker metadata
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-      # Build and push Docker image with Buildx (don't push on PR) ##L82 is added  for duplicate directory
-      # https://github.com/docker/build-push-action
-      
-      - name: Build Docker image for gcp-release
+
+      - name: Build Docker image for NonProd Environment
         id: release-build
         if: needs.validate_branch.outputs.op_workflow_name == 'nonprod'
         run: |
@@ -133,7 +127,7 @@ jobs:
           export IMAGE_NAME="$(basename ${{github.repository}}):$TAG_VERSION"
           echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
 
-      - name: Build Docker image for z5-main
+      - name: Build Docker image for Prod Environment
         id: main-build
         if: needs.validate_branch.outputs.op_workflow_name == 'prod'
         run: |
@@ -177,7 +171,6 @@ jobs:
             image=moby/buildkit:v0.10.6
 
       # Login to Docker Hub
-      # https://github.com/docker/login-action
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -191,60 +184,30 @@ jobs:
           command: cves
           image: ${{ env.IMAGE_NAME_WITH_TAG }}
           only-severities: critical,high
-          sarif-file: sarif.output.json
-          summary: true
-      
-      - name: Upload SARIF result
-        id: upload-sarif
-        uses: github/codeql-action/upload-sarif@v2
+          registry: ghcr.io
+
+      - name: Scan the Docker image with Trivy
+        id: trivy-scan
+        uses: aquasecurity/trivy-action@v0.4.0
         with:
-          sarif_file: sarif.output.json
+          image-ref: ${{ env.IMAGE_NAME_WITH_TAG }}
+          format: 'json'
+          output: 'trivy-results.json'
 
-      # - name: Advance Security Compliance Action for your branch
-      #   id: pac-gcp
-      #   uses: advanced-security/policy-as-code@v2.5.0
-      #   with:
-      #     severity: error
-
-      #     # Repository owner/name.
-      #     # This can be setup using a separate repository to the one being analysed
-      #     #  for security compliance
-      #     repository: ${{ github.repository }}
-
-      #     # The owner/repo of where the policy is stored
-      #     # This generally is primarily used for a single repository that defines
-      #     #  your organizations security policy
-      #     policy: org/<repo-name>
-      #     policy-path: policy/advance.yml
-      #     policy-branch: master 
-      #     token: ${{ secrets.PolicyAsCode }}
-      #     action: ${{ needs.validate_branch.outputs.op_pac_action }}
-
-      #     # [optional] Additional arguments
-      #     argvs: --display
-      #     ref: ${{ github.ref }}
-
-      - name: push Docker image to ghcr if no issues
-        if: needs.validate_branch.outputs.op_workflow_name == 'nonprod' && github.event_name =='push'
-        run: |
-          echo " Pushing the Image to ghcr"
-          docker images
-          docker push ${{ env.IMAGE_ID }}:${{ env.tag }}
-
-      # Step 4: Authenticate with Google Cloud for GAR
-      - name: Authenticate with Google Cloud
-        if: env.REGISTRY == env.REGISTRY_GAR
-        uses: google-github-actions/auth@v2
+      - name: Upload Trivy results as artifacts
+        uses: actions/upload-artifact@v3
         with:
-          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+          name: trivy-results
+          path: trivy-results.json
 
-      - name: push Docker image to google artifact registry if no issues
-        if: needs.validate_branch.outputs.op_workflow_name == 'prod' && github.event_name =='push'
+      - name: Push Docker Image to GHCR
+        if: needs.validate_branch.outputs.op_workflow_name == 'nonprod'
         run: |
-          echo "Authenticating to GAR..."
-          gcloud auth configure-docker asia-south1-docker.pkg.dev
-          echo " Pushing the Image to GAR"
-          docker push ${{ steps.main-build.outputs.imageurl }}
+          echo "Pushing image to GitHub Container Registry"
+          docker push $IMAGE_ID:$TAG_VERSION
 
-
-   
+      - name: Push Docker Image to GAR
+        if: needs.validate_branch.outputs.op_workflow_name == 'prod'
+        run: |
+          echo "Pushing image to Google Artifact Registry"
+          docker push $IMAGE_ID:$TAG_VERSION
